Mobile-portfoliofinish
richie1988/mobile-portfoliofinish pull request #2
Opened 2023-04-27 22:36 UTC by richie1988

added the form part
added about section
added projects button
added the footer section

2023-04-27 23:43 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @richie1988 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️

- [ OPTIONAL] Kindly make sure you use the appropriate background color for your card section  to make your design stick to the figma design :+1: 

- Please bring back the home pages the objectify is to finish the mobile version of your portfolio so you need also the home page and that nav barre so please bring them back as it was for the first project :+1: 
- Kindly is not needed to add the contact form as it has not yet part of the requirement please remove it you will work on it in the next project with a better understanding of all material :+1: 
- Kindly check the structure of your code, there are a few things you need to improve, please go through this lesson to learn how to use different tags in HTML, `<ul>,<li>,<a>,<section>, etc...` and restructure  your code correctly to make it looks more professional  :+1: 

_Check the comments under the review._

## Optional suggestions

- Please make sure in future all the changes you did are present in the current branche you submit for review so that I can easily give you inline comment :+1: 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-28 16:03 UTC, divinecharlotte requested changes
Hi @richie1988    , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 
- linters are passing 👍
- descriptive pr 👍 





 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️



_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 19:33 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @richie1988 , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Great work on making the changes requested by a previous reviewer 👏 
You've done really well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Highlights 
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 19:33 UTC, ABDULALI3468 commented on index.html
> +            </section>
Actually, the last reviewer's instructions mean the following code. I a describing you because the last reviewer did not do well so please consider making your code like the following:-

Please consider following these 2 rules in this section as it's a good practice for semantics:-

1. The technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`
2. The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`


## Solution with a detailed demonstration:-

Following is the code representation of the above if you are confused about what the instructions mean:-


```
    <ul>
      <li>
        Languages
        <ul>
          <li>JavaScript</li>
          <li>Ruby</li>
          <li>Html</li>
          <li>CSS</li>
        </ul>
      </li>
      <li>
        Frameworks
        <ul>
          <li>Bootstrap</li>
          <li>Ruby on Rails</li>
          <li>Rspec</li>
          <li>Capybara</li>
          <li>Selenium</li>
        </ul>
      </li>
      <li>
        Skills
        <ul>
          <li>Database Management</li>
          <li>Version Control</li>
          <li>CLI</li>
          <li>API Design</li>
          <li>Web Development</li>
        </ul>
      </li>
    </ul>
```

2023-04-28 19:33 UTC, ABDULALI3468 commented on index.html
> +                <a href="#home" class="active"><img src="pics/My Logo.png" alt="MyLogo"></a>
Please consider following the instructions correctly by correctly using the semantic HTML tags. You have used `section tags` a lot but The container of the section is a section tag because

It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.

### CODE REPRESENTATION OF SEMANTIC TAGS FOR YOUR CASE:-

```
  <header>
      <a href="/" class="logo">MY LOGO</a>
      <nav>
        <img src="./hamburgericon.png" alt="" />
      </nav>
    </header>

    <main>
      <section class="headline-section">CONTENT RELATED TO HEADLINE</section>
      <section class="work-section" style="display: grid;">
        CONTENT RELATED TO WORK
        <div class="work-container">CARD CONTENT...</div>
        <div class="work-container">CARD CONTENT...</div>
        <div class="work-container">CARD CONTENT...</div>
        <div class="work-container">CARD CONTENT...</div>
      </section>
      <section class="about-section">CONTENT RELATED TO ABOUT</section>
    </main>

    <footer></footer>
```

2023-04-28 19:36 UTC, ABDULALI3468 commented
@richie1988 As you told the previous reviewer @divinecharlotte was not able to describe clearly I tried my best to do it. I hope everything is cleared now ✅

2023-04-28 21:39 UTC, richie1988 commented on index.html
> +                <a href="#home" class="active"><img src="pics/My Logo.png" alt="MyLogo"></a>
you mean to take them out from the class so then can be just li?

2023-04-29 06:17 UTC, Efiamotu-1 approved these changes
Hi @richie1988 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct GitHub flow or Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

- [ ] Going further you are also required to always name your branch descriptively in relation to the milestone you are working or the changes your are going to make in that branch for example names like `add_desktop_version` is a good branch name when you are working on creating a works section for your portfolio using names like `portfoliotwo` is not professional so please take note. your earlier reviewers were graceful enough to still review your projects for this error, in your following projects this might not be so, so just take note of this :+1:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 06:17 UTC, Efiamotu-1 commented on README.md
>  _NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
[OPTIONAL]
- [ ] This section should not be part of your readme file, it currently describes how you should create a license for your project and once this is done you are expected to remove it please kindly do so. :+1:

2023-04-29 06:17 UTC, Efiamotu-1 commented on style.css
[OPTIONAL]
- [ ] Creating button interactions for your project is a project requirement which you are required to implement please do it before moving on to your next milestone as you would be needing it. see the below figma design for how they should look
![active-1](https://user-images.githubusercontent.com/89055502/235286841-2a0975bf-edbd-490d-b295-6bdbee2325b3.png)
- [ ] you are expected to use psuedo classes in css such as ::active, ::hover` to achieve this please make sure to implement before merging your branch :+1:

2023-04-29 06:17 UTC, Efiamotu-1 commented on style.css
[OPTIONAL]
- [ ] I would also plead with you to implement the works section to look exactly like the figma template centered at the middle not close to the left like you have done it, see the figma image and yours below.
> - figma design 
![recent-f](https://user-images.githubusercontent.com/89055502/235286904-5f05f873-0adf-43dd-a992-d04e010f1443.png)
> - student design
![recent-s](https://user-images.githubusercontent.com/89055502/235286916-50f82547-d1f6-41d3-b2eb-fb9d2306930f.png)

2023-04-29 06:17 UTC, Efiamotu-1 commented on index.html
[OPTIONAL]
- [ ] in implementing the last reviewers requirement, you didn't completely get the structure of your html document. 
```
   <header>
       <a href="/" class="logo">MY LOGO</a>
       <nav>
         <img src="./hamburgericon.png" alt="" />
       </nav>
     </header>
 
     <main>
       <section class="headline-section">
             CONTENT RELATED TO HEADLINE 
       </section>
       <section class="work-section" style="display: grid;">
         CONTENT RELATED TO WORK
         <div class="work-container">CARD CONTENT...</div>
         <div class="work-container">CARD CONTENT...</div>
         <div class="work-container">CARD CONTENT...</div>
         <div class="work-container">CARD CONTENT...</div>
       </section>
       <section class="about-section">CONTENT RELATED TO ABOUT</section>
     </main>
 
     <footer></footer>
 ```
- [ ] above is how it should look, but in your code you started by adding the main first and putting the header inside the main, this is not the convention, the convention is how it has been shown above first you have the header, followed by the main which would contains multiple sections and then you have your footer please correct your codebase to reflect this change.

2023-04-29 09:49 UTC, merged