Portfoliofinish-contactform#1
richie1988/mobile-portfoliofinish pull request #7
Opened 2023-05-09 17:56 UTC by richie1988

added Contact form
added input field
implemented the html tag
added text area filled

2023-05-09 18:37 UTC, aamirkhan2478 requested changes
Hi @richie1988 , 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 18:37 UTC, aamirkhan2478 commented on index.html
> +                    <textarea name="subject" placeholder="Write me something..." required></textarea>
- [ ] Well done :clap: you did a very nice job :+1:  but you forget `maxlength='500'` in the `textarea` field so kindly add `maxlength='500'` in the `textarea` field because this is a requirement so kindly fix it :slightly_smiling_face: 

_**Requirement**_
- Message field accepts up to 500 chars.

2023-05-09 18:37 UTC, aamirkhan2478 commented on index.html
>                  </form>
- [ ] Please stick to the Figma design you did implement all button effects in your whole project so kindly add it checks below :point_down: all button effects :slightly_smiling_face: 

![Screenshot from 2023-02-21 23-13-53](https://github.com/richie1988/mobile-portfoliofinish/assets/45226848/db382308-cba9-444d-a895-33aae4f0192d)

2023-05-09 19:28 UTC, aamirkhan2478 requested changes
Hi @richie1988 , 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linters passed
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 19:28 UTC, aamirkhan2478 commented on index.html
> +                    <button class="submit">Get in touch</button>
- [ ] Well done you did some changes but button interactions such as hover, active (when it's pressed), disabled and enable (default state) are styled as shown in the Figma template. Still, your button effects are not applied so kindly apply all button effects :slightly_smiling_face: 

![Screenshot from 2023-02-21 23-13-53](https://github.com/richie1988/mobile-portfoliofinish/assets/45226848/1f76ade4-1ce2-4330-9023-5a65f98b0cde)

2023-05-09 23:55 UTC, DuaneDave requested changes
Hi @richie1988 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Correct workflow used
✔️ Form correctly set up

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-09 23:55 UTC, DuaneDave commented on index.html
> +                    <button class="submit ">Get in touch</button>
As previously requested, the interactions for this button should be done according to this [guideline](https://user-images.githubusercontent.com/45226848/237199987-1f76ade4-1ce2-4330-9023-5a65f98b0cde.png) in order to make your design look similar to the template.

To implement this, use:
```
.submit:hover for the hover state

.submit:active for the pressed
```

NOTE: instead of scaling the button up, it is better to change the background color to the on the specific state in the figma template.

2023-05-10 08:57 UTC, wayungi approved these changes
Hi @richie1988 , 

![image](https://user-images.githubusercontent.com/99656687/220082459-c1b049c7-5498-42e7-942b-ec7a05d3e603.png)

Great work, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**Remember: Every finish line 🏁  is the beginning of a new race 🐎** 

## Highlights
- [ ]  Very good implementation of the button states ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-10 08:57 UTC, wayungi commented on index.html
> +                <form action="https://formspree.io/f/mrgvjnke " method="post ">
- [ OPTIONAL] Kindly the spaces on the method & action values. the form is not posted. below is the message I get from form spree.
![spree](https://github.com/richie1988/mobile-portfoliofinish/assets/99656687/b24975e6-7124-4d44-9764-5e4af671fa24)

2023-05-10 08:57 UTC, wayungi commented on index.html
> +                    <button class="submit ">Get in touch</button>
- [ OPTIONAL] Your form validations are not working because you included extra space in the values. `" maxlength="30 "`

2023-05-10 09:38 UTC, richie1988 commented on index.html
> +                <form action="https://formspree.io/f/mrgvjnke " method="post ">
Thanks a lot for your insight

2023-05-10 09:55 UTC, merged